/* Reisblik 8.8.9 — Backup content terugzetten inclusief Mijn agenda */
(function(){"use strict";
const BACKUP_KEYS=[{key:"reisblik_visited_v1",label:"Bezocht"},{key:"ruinekerk_extra_info_v1",label:"Extra informatie"},{key:"ruinekerk_extra_simple_v1",label:"Eenvoudige Extra informatie"},{key:"ruinekerk_notes_v1",label:"Persoonlijke notities en ervaringen"},{key:"ruinekerk_user_locations_v1",label:"Eigen locaties"},{key:"reisblik_agenda_evenementen_v1",label:"Mijn agenda evenementen"}];
let selectedBackup=null;
function countItems(v){if(Array.isArray(v))return v.length;if(v&&typeof v==="object")return Object.values(v).reduce((t,i)=>t+(Array.isArray(i)?i.length:1),0);return v===null?0:1;}
function validateBackup(b){if(!b||typeof b!=="object")throw new Error("Ongeldige backup.");if(b.backupType!=="Reisblik persoonlijke lokale content")throw new Error("Dit is geen geldige Reisblik-contentbackup.");if(!b.data||typeof b.data!=="object")throw new Error("De backup bevat geen gegevens.");if(!b.summary||!Array.isArray(b.summary.categories))throw new Error("De backup bevat geen geldige samenvatting.");return true;}
function preview(b){const total=BACKUP_KEYS.reduce((s,i)=>s+countItems(b.data[i.key]),0);return "Backup versie "+(b.applicationVersion||"onbekend")+"<br>"+BACKUP_KEYS.map(i=>i.label+": "+countItems(b.data[i.key])).join("<br>")+"<br><strong>Totaal: "+total+" gegevensitems</strong>";}
function restore(){if(!selectedBackup)return;if(!confirm("Weet je zeker dat je deze backup wilt terugzetten? De geselecteerde Reisblik-content wordt overschreven door de gegevens uit de backup."))return;BACKUP_KEYS.forEach(i=>{const v=selectedBackup.data[i.key];if(v===null||typeof v==="undefined")localStorage.removeItem(i.key);else localStorage.setItem(i.key,JSON.stringify(v));});const st=document.getElementById("restoreStatus");if(st)st.textContent="✅ Backup teruggezet. Reisblik wordt opnieuw geladen.";setTimeout(()=>window.location.reload(),700);}
function init(){const open=document.getElementById("restoreOpenBtn"),modal=document.getElementById("restoreModal"),file=document.getElementById("restoreFile"),prev=document.getElementById("restorePreview"),btn=document.getElementById("restoreConfirmBtn"),close=document.getElementById("restoreCloseBtn");if(!open||!modal||!file||!btn||!close)return;if(open.dataset.restoreBound==="true")return;open.dataset.restoreBound="true";function closeModal(){modal.style.display="none";selectedBackup=null;file.value="";btn.disabled=true;if(prev)prev.innerHTML="";const st=document.getElementById("restoreStatus");if(st)st.textContent="";open.focus();}open.addEventListener("click",()=>{modal.style.display="block";file.focus();});close.addEventListener("click",closeModal);modal.addEventListener("click",e=>{if(e.target===modal)closeModal();});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&modal.style.display!=="none")closeModal();});file.addEventListener("change",()=>{selectedBackup=null;btn.disabled=true;if(prev)prev.innerHTML="";const f=file.files&&file.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const b=JSON.parse(r.result);validateBackup(b);selectedBackup=b;if(prev)prev.innerHTML=preview(b);btn.disabled=false;}catch(e){if(prev)prev.textContent="⚠️ Ongeldige backup: "+e.message;}};r.onerror=()=>{if(prev)prev.textContent="⚠️ Het backupbestand kon niet worden gelezen.";};r.readAsText(f);});btn.addEventListener("click",restore);}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();})();
